"""Demonstrate the initial data preparation modules with a user-supplied CSV."""

from src.purchase_propensity.utils.config import CONFIG, PROJECT_ROOT

from purchase_propensity.data.loader import load_dataset
from purchase_propensity.utils.logger import get_logger


def main() -> None:
    """Load and validate the prepared training and test datasets.

    Prepared datasets are generated by the DVC pipeline. This entry point
    consumes those artifacts without repeating data preparation.

    Raises:
        FileNotFoundError: If either prepared dataset is missing.
        ValueError: If either prepared dataset is empty.
    """
    logger = get_logger(__name__)

    prepared_path = PROJECT_ROOT / CONFIG["data"]["prepared_path"]
    train_path = prepared_path / CONFIG["data"]["train_dataset_file"]
    test_path = prepared_path / CONFIG["data"]["test_dataset_file"]

    train_data = load_dataset(train_path)
    test_data = load_dataset(test_path)

    if train_data.empty:
        msg = f"Training dataset is empty: {train_path}"
        raise ValueError(msg)

    if test_data.empty:
        msg = f"Test dataset is empty: {test_path}"
        raise ValueError(msg)

    logger.info(
        "Dados preparados carregados: %d linhas de treino, "
        "%d linhas de teste, %d features e target '%s'.",
        len(train_data),
        len(test_data),
        len(train_data.columns) - 1,
        CONFIG["model"]["target_column"],
    )


if __name__ == "__main__":
    main()
